HelloWorld.class: HelloWorld.java
	javac $^
HelloWorld: HelloWorld.class
	java $@


Counting.class: Counting.java
	javac $^
Counting: Counting.class
	java $@


Puzzle.class: Puzzle.java
	javac $^
Puzzle: Puzzle.class
	java $@


Philosopher.class: Philosopher.java
	javac $^
Philosopher: Philosopher.class
	java $@


PhilosopherLockOrder.class: PhilosopherLockOrder.java
	javac $^
PhilosopherLockOrder: PhilosopherLockOrder.class
	java $@


HttpDownload.class: HttpDownload.java
	javac $^
HttpDownload: HttpDownload.class
	java $@


clean:
	rm -rf *.class
	rm -rf *.out
