Uninterruptible.class: Uninterruptible.java
	javac $^
Uninterruptible: Uninterruptible.class
	java $@

Interruptible.class: Interruptible.java
	javac $^
Interruptible: Interruptible.class
	java $@

PhilosopherTimeout.class: PhilosopherTimeout.java
	javac $^
PhilosopherTimeout: PhilosopherTimeout.class
	java $@

ConcurrentSortedList.class: ConcurrentSortedList.java
	javac $^
ConcurrentSortedList: ConcurrentSortedList.class
	java $@

PhilosopherCondition.class: PhilosopherCondition.java
	javac $^
PhilosopherCondition: PhilosopherCondition.class
	java $@

CountingAtomic.class: CountingAtomic.java
	javac $^
CountingAtomic: CountingAtomic.class
	java $@

# self study code
SingleLockConcurrentSortedList.class: SingleLockConcurrentSortedList.java
	javac $^
SingleLockConcurrentSortedList: SingleLockConcurrentSortedList.class
	java $@

PhilosopherWaitNotify.class: PhilosopherWaitNotify.java
	javac $^
PhilosopherWaitNotify: PhilosopherWaitNotify.class
	java $@	

clean:
	rm -rf *.class
	rm -rf *.out
