CLOJURE := java -jar d:\bin\clojure-1.8.0\clojure-1.8.0.jar

all: sum wordcount optimized-recursive-sum macro

sum:
	$(CLOJURE) sum.clj

wordcount:
	$(CLOJURE) wordcount.clj

optimized-recursive-sum:
	$(CLOJURE) optimized-recursive-sum.clj

macro:
	$(CLOJURE) macro.clj

