CLOJURE := java -jar d:\bin\clojure-1.8.0\clojure-1.8.0.jar

all: wordcount reducers parallel_frequencies

wordcount:
	$(CLOJURE) wordcount.clj

reducers:
	$(CLOJURE) reducers.clj

parallel_frequencies:
	$(CLOJURE) parallel_frequencies.clj
