EchoServer_SimpleThread.class: EchoServer_SimpleThread.java
	javac $^
EchoServer_SimpleThread: EchoServer_SimpleThread.class
	java $@

EchoServer_ThreadPool.class: EchoServer_ThreadPool.java
	javac $^
EchoServer_ThreadPool: EchoServer_ThreadPool.class
	java $@

HttpDownload.class: HttpDownload.java
	javac $^
HttpDownload: HttpDownload.class
	java $@


clean:
	rm -rf *.class
	rm -rf *.out

