CLOJURE	:= java -jar ~/bin/clojure.jar

all:

agent: agent.clj
	$(CLOJURE) $^

agent_with_sleep: agent_with_sleep.clj
	$(CLOJURE) $^

agent_error: agent_error.clj
	$(CLOJURE) $^

stm: stm.clj
	$(CLOJURE) $^
