all:	\
	hello_actors	\
	hello_actors2	\
	counter	\
	counter2	\
	counter3

hello_actors: hello_actors.exs
	elixir $^

hello_actors2: hello_actors2.exs
	elixir $^

counter: counter.ex
	elixir $^

counter2: counter2.ex
	elixir $^

counter3: counter3.ex
	elixir $^

parallel: parallel.ex
	elixir $^

parallel_reduce: parallel_reduce.ex
	elixir $^
