CLOJURE	:= java -jar ~/bin/clojure.jar

all: atom persistent validator watcher

atom: atom.clj
	$(CLOJURE) $^

persistent: persistent.clj
	$(CLOJURE) $^

validator: validator.clj
	$(CLOJURE) $^

watcher: watcher.clj
	$(CLOJURE) $^
